-- Canonical D1 schema is versioned in ./migrations.
-- Apply migrations in lexical order. Current baseline:
--   migrations/0001_runtime_foundation.sql
--   migrations/0002_rating_aggregate_triggers.sql
